"""
The determinism pins reach a REAL deploy surface (item 9b / task group 7).

``GUARDRAIL_EXPECTED_CONFIG_DIR_DIGEST`` and ``GUARDRAIL_EXPECTED_UV_LOCK_SHA256``
were read by ``app.settings`` and populated by nothing: the pod had no entry in
``docker-compose.yml`` and no K8s manifest, so "the pod refuses to serve on drift"
existed only inside ``test_digest_enforcement.py``. These tests hold the two deploy
surfaces to the contract that closes that gap:

- both pins, ``GUARDRAIL_MODEL_ID`` and ``GUARDRAIL_REGION`` are carried;
- the pin VALUES come from the single generated source
  (``deploy/guardrail-pins.env``) and are never hand-copied — a literal in a
  compose file dies at the pod boundary, and compose is dev-only;
- the same generated bytes render a ConfigMap Kubernetes can consume;
- no AWS credential literal appears in any deploy config (ambient chain only);
- pins injected the way a deploy surface injects them + a drifted ``config/``
  makes lifespan self-verification fail, so ``/readyz`` never goes ready.

No AWS, no Docker, no live pod. The live end-to-end run of the last case against a
real uvicorn process is ``scripts/demo_refuse_to_serve.sh``.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

import pytest
import yaml
from app.config_digest import (
    DigestMismatchError,
    compute_config_dir_digest,
    compute_lock_sha256,
    default_config_dir,
    default_lock_path,
    default_pin_env_path,
    read_pin_env,
)
from app.main import app
from fastapi.testclient import TestClient

REPO_ROOT = Path(__file__).resolve().parents[3]
DEPLOY_DIR = Path(__file__).resolve().parents[1] / "deploy"
COMPOSE_PATH = REPO_ROOT / "docker-compose.yml"
KUSTOMIZATION_PATH = DEPLOY_DIR / "kustomization.yaml"
DEPLOYMENT_PATH = DEPLOY_DIR / "k8s" / "deployment.yaml"
SERVICE_PATH = DEPLOY_DIR / "k8s" / "service.yaml"
SERVICEACCOUNT_PATH = DEPLOY_DIR / "k8s" / "serviceaccount.yaml"

PIN_KEYS = ("GUARDRAIL_EXPECTED_CONFIG_DIR_DIGEST", "GUARDRAIL_EXPECTED_UV_LOCK_SHA256")
# Every committed deploy artifact that could carry a pin or a credential.
DEPLOY_FILES = (
    COMPOSE_PATH,
    KUSTOMIZATION_PATH,
    DEPLOYMENT_PATH,
    SERVICE_PATH,
    SERVICEACCOUNT_PATH,
)
# Env names that would mean a static key was injected, plus the shape of an
# access key id itself. AWS_PROFILE / AWS_REGION are NOT credentials.
CREDENTIAL_ENV_NAMES = (
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_SESSION_TOKEN",
    "aws_secret_access_key",
)
ACCESS_KEY_ID_PATTERN = re.compile(r"(AKIA|ASIA)[0-9A-Z]{16}")
# Valid ConfigMap data key (and therefore a valid env var name for envFrom).
CONFIGMAP_KEY_PATTERN = re.compile(r"^[-._a-zA-Z][-._a-zA-Z0-9]*$")


def _compose_guardrail_service() -> dict:
    """The guardrail service block from the repo-root compose file."""
    compose = yaml.safe_load(COMPOSE_PATH.read_text(encoding="utf-8"))
    assert "guardrail" in compose["services"], (
        "the guardrail pod has no entry in docker-compose.yml — with no deploy "
        "surface nothing can populate the determinism pins"
    )
    return compose["services"]["guardrail"]


def _environment_map(entries: list[str]) -> dict[str, str]:
    """Compose ``KEY=value`` / bare ``KEY`` entries as a mapping."""
    resolved: dict[str, str] = {}
    for entry in entries:
        key, _, value = entry.partition("=")
        resolved[key] = value
    return resolved


def test_compose_service_carries_both_pins_the_model_id_and_the_region():
    """Compose sources both pins from the generated file and sets model + region."""
    service = _compose_guardrail_service()

    declared = service["env_file"]
    declared = [declared] if isinstance(declared, str) else declared
    resolved = [(COMPOSE_PATH.parent / path).resolve() for path in declared]
    assert default_pin_env_path().resolve() in resolved, (
        "compose must read the pins from the single generated source"
    )

    environment = _environment_map(service["environment"])
    assert "au.anthropic.claude-haiku-4-5-20251001-v1:0" in environment["GUARDRAIL_MODEL_ID"]
    assert "ap-southeast-2" in environment["GUARDRAIL_REGION"]
    # The pins arrive through env_file, so they must NOT also be listed here.
    assert not set(PIN_KEYS) & set(environment)


def test_no_deploy_file_hand_copies_a_pin_value():
    """A pin value appears in the generated source and nowhere else."""
    pins = read_pin_env(default_pin_env_path())
    assert set(pins) == set(PIN_KEYS)

    for path in DEPLOY_FILES:
        text = path.read_text(encoding="utf-8")
        for key, value in pins.items():
            assert value not in text, (
                f"{path.name} hand-copies {key}; a literal pin goes stale on the "
                "next config/ edit and dies at the pod boundary"
            )


def test_no_aws_credential_literal_appears_in_any_deploy_config():
    """Credentials come from the ambient chain; config never carries key material."""
    for path in (*DEPLOY_FILES, default_pin_env_path()):
        text = path.read_text(encoding="utf-8")
        for name in CREDENTIAL_ENV_NAMES:
            assert name not in text, f"{path.name} injects a static credential ({name})"
        assert not ACCESS_KEY_ID_PATTERN.search(text), (
            f"{path.name} contains an AWS access key id literal"
        )


def test_the_generated_source_renders_a_configmap_kubernetes_can_consume():
    """The same bytes compose reads render a valid, live-accurate ConfigMap."""
    pins = read_pin_env(default_pin_env_path())
    # What `kubectl create configmap --from-env-file` / kustomize's
    # configMapGenerator produce from those bytes.
    configmap = {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {"name": "guardrail-pins"},
        "data": pins,
    }
    round_tripped = yaml.safe_load(yaml.safe_dump(configmap))

    assert round_tripped["data"] == pins
    for key, value in round_tripped["data"].items():
        assert CONFIGMAP_KEY_PATTERN.match(key), f"{key} is not a valid ConfigMap key"
        assert isinstance(value, str)
    # The published pins are the LIVE truth, so the ConfigMap a cluster would get
    # is the one this pod's own config/ and uv.lock hash to.
    assert round_tripped["data"]["GUARDRAIL_EXPECTED_CONFIG_DIR_DIGEST"] == (
        compute_config_dir_digest(default_config_dir())
    )
    assert round_tripped["data"]["GUARDRAIL_EXPECTED_UV_LOCK_SHA256"] == (
        compute_lock_sha256(default_lock_path())
    )


def test_the_k8s_manifests_consume_that_same_generated_source():
    """Kustomize generates the pins ConfigMap from the file compose reads."""
    kustomization = yaml.safe_load(KUSTOMIZATION_PATH.read_text(encoding="utf-8"))
    generators = {entry["name"]: entry for entry in kustomization["configMapGenerator"]}
    resolved = [
        (KUSTOMIZATION_PATH.parent / path).resolve()
        for path in generators["guardrail-pins"]["envs"]
    ]
    assert resolved == [default_pin_env_path().resolve()]

    deployment = yaml.safe_load(DEPLOYMENT_PATH.read_text(encoding="utf-8"))
    container = deployment["spec"]["template"]["spec"]["containers"][0]
    assert {"guardrail-pins"} == {
        source["configMapRef"]["name"] for source in container["envFrom"]
    }
    env = {entry["name"]: entry["value"] for entry in container["env"]}
    assert env["GUARDRAIL_MODEL_ID"] == "au.anthropic.claude-haiku-4-5-20251001-v1:0"
    assert env["GUARDRAIL_REGION"] == "ap-southeast-2"
    # Readiness is the surface the refuse-to-serve guarantee shows up on.
    assert container["readinessProbe"]["httpGet"]["path"] == "/readyz"
    assert container["livenessProbe"]["httpGet"]["path"] == "/healthz"


def test_deploy_surface_pins_plus_a_drifted_config_never_go_ready(tmp_path, monkeypatch):
    """Pins injected as a deploy surface injects them + drift ⇒ refuse to serve."""
    _clear_app_state()

    drifted_config = tmp_path / "config"
    shutil.copytree(default_config_dir(), drifted_config)
    config_yml = drifted_config / "config.yml"
    config_yml.write_text(
        config_yml.read_text(encoding="utf-8") + "\n# deliberate drift\n",
        encoding="utf-8",
    )

    for key, value in read_pin_env(default_pin_env_path()).items():
        monkeypatch.setenv(key, value)
    monkeypatch.setenv("GUARDRAIL_CONFIG_DIR", str(drifted_config))

    try:
        with pytest.raises(DigestMismatchError, match="REFUSES to serve"):
            with TestClient(app):
                pass
        # Startup aborted before the engine was built, so readiness is an honest
        # 503 — the pod never becomes ready under a drifted config/.
        response = TestClient(app).get("/readyz")
        assert response.status_code == 503
        assert "not initialized" in response.json()["detail"]
    finally:
        _clear_app_state()


def _clear_app_state() -> None:
    """Drop every lifespan-populated slot so state never leaks between tests."""
    for slot in ("settings", "rails", "detectors", "detectors_error"):
        if hasattr(app.state, slot):
            delattr(app.state, slot)
